import React from "react";
import { Metadata } from "next";
import ComPage from "@/components/comparison/ComPage";

export const metadata:Metadata = {
  title: "Comparison",
  description: "Generated by Next.js",
};

const ComparisonPage = () => {

  return (
    <section>
      <ComPage />
    </section>
  );
};

export default ComparisonPage;
