import React from "react";
import { Metadata } from "next";
import ComparisonWrapper from "@/components/comparison/ComparisonWrapper";

export const metadata: Metadata = {
  title: "Comparison",
  description: "Generated by Next.js",
};

export default function ComparisonPage() {
  return (
    <section>
      <ComparisonWrapper />
    </section>
  );
}
