import React from "react";
import { Metadata } from "next";
import InterestWrapper from "@/components/interest/InterestWrapper";

export const metadata: Metadata = {
  title: "Interest Calculator",
  description: "Generated by Next.js",
};

export default function InterestCalcPage() {
  return (
    <section>
      <InterestWrapper />
    </section>
  );
}
