import React from "react";
import { Metadata } from "next";
import { PeopleProvider } from "@/contexts/sharebill/PeopleContext";
import { OrderProvider } from "@/contexts/sharebill/OrderContext";
import TabContainer from "@/components/sharebill/TabContainer";

export const metadata:Metadata = {
  title: "Fair Share",
  description: "Generated by Next.js",
};

const ShareBillPage = () => {
  return (
    <>
      <PeopleProvider>
        <OrderProvider>
          <TabContainer />
        </OrderProvider>
      </PeopleProvider>
    </>
  );
};

export default ShareBillPage;
